apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
        - name: guestbook
          image: quay.io/gas_stocktrader/guestbook:afee33f41e97a21757618fb009458a1b2a2b268c
          envFrom:
            - configMapRef:
                name: guestbook-config
            - secretRef:
                name: guestbook-secret
          ports:
            - containerPort: 9080
            - containerPort: 9443
