apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
        - name: guestbook
          image: quay.io/gas_stocktrader/guestbook:510bda5f17f44e39872f8676e34b2883b72dd00d
          envFrom:
            - configMapRef:
                name: guestbook-config
          env:
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: guestbook-secret
                  key: PG_USER
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: guestbook-secret
                  key: PG_PASSWORD
          ports:
            - containerPort: 9080
            - containerPort: 9443
