# This workflow will:
# - create sat config version
#
### Before you begin:
# - Create sat config in IBM Cloud
# - ...

# Name of the workflow
name: Update Sat Config

on: 
  workflow_dispatch:
  
# Environment variables available to all jobs and steps in this workflow
env:
  # EDIT secrets with with your registry, registry path, and apikey
  REGISTRY: quay.io
  REGISTRY_NAMESPACE: gas_stocktrader
  # EDIT with your registry username.
  REGISTRY_USER: gas_stocktrader+quaytrader
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
  IMAGE_NAME: guestbook
  
  GITHUB_SHA: d914ff6b6c196e2ef3c648b66a5287758b90d4f1
  
  GITOPS_REPO: stocktrader-ops/guestbook
  GITOPS_DIR: manifests
  GITOPS_USERNAME: ${{ secrets.GITOPS_USERNAME }}
  GITOPS_TOKEN: ${{ secrets.GITOPS_TOKEN }}  
  
  # Sat config env
  SAT_CHANNEL_UUID: ${{ secrets.SAT_CHANNEL_UUID }}
  IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
  
jobs:
  quay-scan:
    runs-on: ubuntu-latest
    steps:
    # Scan image   
    - name: Scan image
      run: |
        IMAGE_DIGEST=`skopeo inspect docker://"$REGISTRY"/"$REGISTRY_NAMESPACE"/"$IMAGE_NAME":"$GITHUB_SHA" | jq -r .Digest`
        echo "digest: $IMAGE_DIGEST"
        
        curl -o `basename $IMAGE_NAME`.json https://quay.io/api/v1/repository/"$REGISTRY_NAMESPACE"/$IMAGE_NAME/manifest/$IMAGE_DIGEST/security?vulnerabilities=true
       
        ls -la
        cat guestbook.json
        
        jq '.data.Layer.Features[]' `basename $IMAGE_NAME`.json | jq -c '{"Name":.Name,"Version":.Version,"Advisory":.Vulnerabilities[]} | select(.Advisory.Severity=="High") | {"Advisory":.Advisory.Name,"Link":.Advisory.Link,"PACKAGE":.Name,"CURRENT VERSION":.Version,"FIXED IN VERSION":.Advisory.FixedBy }'
        

      
      
  push-sat-config:
    runs-on: ubuntu-latest
    steps:
    # Checkout repo   
    - name: Checkout
      uses: actions/checkout@v2    
    # Create new version
    - name: Update Sat Config
      uses: IBM/satellite-config-actions@v1
      with:
        apikey: '${IBM_CLOUD_API_KEY}'
        filename: 'manifests/guestbook-deployment.yaml'
        channel_id: '${SAT_CHANNEL_UUID}'
        version_name: 'guestbook-v${GITHUB_SHA}'
